# Generated by Django 3.2.10 on 2022-03-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='balance',
            field=models.FloatField(),
        ),
    ]
