# Generated by Django 3.2.10 on 2022-03-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain',
            name='latestBlock',
        ),
    ]
