# Generated by Django 3.2.10 on 2022-03-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_blockchain_latestblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockchain',
            old_name='genesisBlock',
            new_name='latestBlock',
        ),
    ]
