# Generated by Django 3.2.10 on 2022-03-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_genesisblock_blockchain_latestblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain',
            name='latestBlock',
        ),
    ]
