# Generated by Django 3.2.10 on 2022-03-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_blockchain_latestblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='previousId',
            new_name='previousHash',
        ),
        migrations.AddField(
            model_name='block',
            name='id',
            field=models.IntegerField(default=4, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(max_length=255),
        ),
    ]
